/* DOMINIO: VENTA - COMPRA Y SUMINISTRO DE SERVICIOS DE CONSTRUCCION
PENDIENTE:

    1.- DESARROLLAR REGLAS DE NEGOCIOS DE ACUERDO A PROCESOS INTERNOS DEL SISTEMA
    COMPRA - VENTA - PRESTACION DE SERVICIO - REGISTRACION - ETC.
    2.- DESARROLLAR RESPECTIVOS ACCIONARES EN COMMANDS
    3.- POLITICAS - LIMITACIONES - [DIAGRAMA DE FLUJO POR FUNCIONALIDADES]
*/